/**
 * Comprehensive icon tag enrichment system.
 *
 * Analyses every icon's **name** (case-insensitive word splitting) to produce
 * additional tags that align with popular UI metaphors.
 *
 * Design-system icon libraries typically follow naming conventions like
 * "arrow-right-circle-fill".  The enrichment splits those names into tokens
 * and then adds semantically-related search tags so that designers can locate
 * icons by *meaning* regardless of the exact name used.
 */

import type { IconItem } from "./data-store";

// ──────────────────────────────────────────────────────────────
// 1.  NAME-KEYWORD → ADDITIONAL TAGS
//     Each key is a word that may appear in an icon name.
//     The value is an array of search tags to add.
//     Tags are rebuilt deterministically from the icon name.
// ──────────────────────────────────────────────────────────────

const NAME_TAG_MAP: Record<string, string[]> = {
  /* ── Arrows & Direction ──────────────────────────────── */
  arrow:        ["direction", "pointer", "navigate"],
  right:        ["forward", "next", "east"],
  left:         ["back", "previous", "west", "return"],
  up:           ["north", "ascend", "top"],
  down:         ["south", "descend", "bottom", "dropdown"],
  chevron:      ["caret", "arrow", "expand", "collapse", "angle"],
  caret:        ["chevron", "arrow", "dropdown"],
  expand:       ["open", "grow", "enlarge", "maximize"],
  collapse:     ["close", "shrink", "minimize"],
  sort:         ["order", "arrange", "rank", "ascending", "descending"],
  swap:         ["exchange", "switch", "reverse", "transfer"],
  move:         ["drag", "reorder", "rearrange"],
  undo:         ["revert", "back", "restore", "previous"],
  redo:         ["repeat", "forward", "redo"],
  refresh:      ["reload", "sync", "update", "rotate", "retry"],
  rotate:       ["turn", "spin", "orientation"],
  flip:         ["mirror", "reverse", "reflect"],

  /* ── Actions ─────────────────────────────────────────── */
  add:          ["plus", "new", "create", "insert"],
  plus:         ["add", "new", "create", "positive", "increase"],
  minus:        ["subtract", "remove", "decrease", "negative"],
  remove:       ["delete", "trash", "discard", "minus"],
  delete:       ["trash", "remove", "discard", "bin", "erase"],
  trash:        ["delete", "remove", "bin", "garbage", "discard", "rubbish"],
  edit:         ["pencil", "modify", "write", "update", "change"],
  pencil:       ["edit", "write", "draw", "compose"],
  pen:          ["write", "edit", "draw", "ink", "compose"],
  eraser:       ["delete", "clear", "remove", "rubber"],
  copy:         ["duplicate", "clone", "replicate", "clipboard"],
  paste:        ["clipboard", "insert"],
  cut:          ["scissors", "trim", "clip"],
  scissors:     ["cut", "trim", "clip", "snip"],
  save:         ["disk", "floppy", "store", "persist", "keep"],
  check:        ["confirm", "done", "approve", "tick", "success", "complete", "yes", "correct", "verified"],
  close:        ["x", "dismiss", "cancel", "exit", "cross", "clear"],
  cancel:       ["close", "stop", "abort", "dismiss"],
  search:       ["find", "magnify", "lookup", "magnifying glass", "discover", "query", "lens"],
  filter:       ["funnel", "refine", "sort", "narrow"],
  zoom:         ["magnify", "enlarge", "scale", "inspect"],
  share:        ["send", "distribute", "forward", "export", "social"],
  download:     ["save", "export", "receive", "get", "install", "arrow down"],
  upload:       ["import", "send", "publish", "arrow up"],
  import:       ["upload", "add", "load", "bring in"],
  export:       ["download", "save", "send out"],
  print:        ["printer", "output", "paper", "document"],
  scan:         ["barcode", "qr", "read", "capture"],
  drag:         ["move", "grab", "handle", "reorder"],
  drop:         ["release", "place", "droppable"],
  pin:          ["attach", "thumbtack", "fix", "location", "map"],
  unpin:        ["detach", "release", "remove"],
  attach:       ["paperclip", "clip", "pin", "connect"],
  paperclip:    ["attach", "attachment", "clip"],
  link:         ["chain", "url", "connect", "hyperlink", "anchor"],
  unlink:       ["disconnect", "break", "detach"],
  external:     ["link", "outside", "new window", "open"],

  /* ── Navigation & Layout ─────────────────────────────── */
  home:         ["house", "main", "start", "dashboard", "landing"],
  menu:         ["hamburger", "bars", "navigation", "drawer", "sidebar", "three lines"],
  hamburger:    ["menu", "bars", "navigation", "three lines"],
  sidebar:      ["panel", "drawer", "navigation", "menu"],
  grid:         ["layout", "tiles", "gallery", "mosaic", "matrix"],
  list:         ["rows", "items", "lines", "queue", "table"],
  table:        ["grid", "spreadsheet", "data", "rows", "columns"],
  columns:      ["layout", "grid", "table"],
  rows:         ["layout", "list", "table"],
  layout:       ["grid", "template", "structure", "arrange"],
  tabs:         ["navigation", "sections", "switch", "panels"],
  tab:          ["navigation", "section", "panel"],
  breadcrumb:   ["navigation", "path", "trail", "hierarchy"],
  pagination:   ["pages", "next", "previous", "navigation"],
  steps:        ["wizard", "progress", "sequence", "workflow"],
  modal:        ["dialog", "popup", "overlay", "window"],
  dialog:       ["modal", "popup", "alert", "window"],
  popover:      ["tooltip", "dropdown", "overlay", "bubble"],
  tooltip:      ["hint", "info", "help", "popover"],
  drawer:       ["panel", "sidebar", "slide", "sheet"],
  panel:        ["section", "pane", "sidebar", "card"],

  /* ── Media & Content ─────────────────────────────────── */
  image:        ["photo", "picture", "gallery", "media"],
  photo:        ["image", "picture", "camera", "gallery"],
  picture:      ["image", "photo", "media"],
  camera:       ["photo", "capture", "shoot", "picture"],
  video:        ["film", "movie", "media", "play", "recording"],
  film:         ["video", "movie", "cinema", "reel"],
  music:        ["audio", "sound", "song", "note", "melody"],
  audio:        ["sound", "music", "speaker", "volume"],
  play:         ["start", "media", "video", "resume", "triangle"],
  pause:        ["stop", "hold", "wait", "media"],
  stop:         ["end", "halt", "media", "square"],
  record:       ["capture", "recording", "dot", "circle"],
  mic:          ["microphone", "voice", "audio", "speak", "record"],
  microphone:   ["mic", "voice", "audio", "speak", "record"],
  speaker:      ["volume", "sound", "audio", "loud"],
  volume:       ["sound", "speaker", "audio", "mute"],
  mute:         ["silent", "volume off", "quiet", "no sound"],
  headphones:   ["audio", "music", "listen", "earbuds"],

  /* ── Communication ───────────────────────────────────── */
  mail:         ["email", "envelope", "message", "inbox", "letter"],
  email:        ["mail", "envelope", "message", "inbox"],
  envelope:     ["mail", "email", "message", "letter"],
  inbox:        ["mail", "messages", "received"],
  send:         ["mail", "paper plane", "submit", "dispatch"],
  message:      ["chat", "comment", "text", "bubble", "conversation"],
  chat:         ["message", "conversation", "bubble", "discuss", "talk"],
  comment:      ["message", "feedback", "note", "annotation"],
  phone:        ["call", "telephone", "contact", "mobile", "dial"],
  call:         ["phone", "telephone", "dial", "ring"],
  video_call:   ["meeting", "conference", "camera"],
  bell:         ["notification", "alert", "alarm", "ring", "reminder"],
  notification: ["bell", "alert", "badge", "update", "new"],
  alert:        ["warning", "notification", "attention", "exclamation"],
  warning:      ["caution", "alert", "exclamation", "danger", "attention"],

  /* ── User & People ───────────────────────────────────── */
  user:         ["person", "profile", "account", "avatar", "member", "human", "contact"],
  users:        ["people", "team", "group", "members", "community"],
  person:       ["user", "profile", "human", "avatar"],
  people:       ["users", "team", "group", "community"],
  team:         ["group", "people", "users", "members", "organization"],
  group:        ["team", "people", "users", "collection", "cluster"],
  profile:      ["user", "account", "avatar", "bio"],
  avatar:       ["user", "profile", "picture", "photo"],
  account:      ["user", "profile", "login", "credential"],

  /* ── Files & Documents ───────────────────────────────── */
  file:         ["document", "page", "paper", "sheet"],
  document:     ["file", "page", "paper", "doc", "text"],
  folder:       ["directory", "organize", "category", "collection"],
  archive:      ["zip", "compress", "package", "box"],
  zip:          ["archive", "compress", "package"],
  clipboard:    ["copy", "paste", "board", "task"],

  /* ── UI Elements ─────────────────────────────────────── */
  button:       ["action", "click", "press", "cta"],
  toggle:       ["switch", "on off", "boolean", "control"],
  switch:       ["toggle", "on off", "boolean"],
  checkbox:     ["check", "select", "tick", "option", "boolean"],
  radio:        ["option", "select", "choice", "dot"],
  slider:       ["range", "control", "adjust", "bar"],
  input:        ["field", "text", "form", "entry"],
  select:       ["dropdown", "choose", "option", "pick", "combobox"],
  dropdown:     ["select", "menu", "option", "list", "popover"],
  badge:        ["tag", "label", "count", "notification", "chip"],
  tag:          ["label", "badge", "chip", "category"],
  chip:         ["tag", "badge", "label", "filter"],
  progress:     ["loading", "bar", "status", "percentage"],
  loading:      ["spinner", "progress", "wait", "processing"],
  spinner:      ["loading", "wait", "processing", "circle"],
  skeleton:     ["loading", "placeholder", "shimmer"],
  divider:      ["separator", "line", "rule", "hr"],
  separator:    ["divider", "line", "rule"],
  card:         ["container", "tile", "box", "panel"],
  accordion:    ["expand", "collapse", "toggle", "section"],
  carousel:     ["slider", "gallery", "slideshow", "swipe"],

  /* ── Status & Feedback ───────────────────────────────── */
  success:      ["check", "done", "approve", "complete", "green"],
  error:        ["danger", "fail", "problem", "red", "bug"],
  info:         ["information", "help", "about", "details", "circle i"],
  help:         ["question", "support", "faq", "info", "assist"],
  question:     ["help", "unknown", "inquiry", "quiz"],
  danger:       ["error", "warning", "critical", "red"],
  caution:      ["warning", "careful", "attention", "alert"],

  /* ── Security & Privacy ──────────────────────────────── */
  lock:         ["security", "password", "private", "locked", "protected", "padlock"],
  unlock:       ["open", "unsecured", "public", "accessible"],
  key:          ["password", "access", "credential", "unlock", "security"],
  shield:       ["security", "protect", "guard", "safe", "defense"],
  eye:          ["view", "visibility", "show", "watch", "see", "preview", "visible"],
  "eye-off":    ["hide", "invisible", "hidden", "privacy", "blind"],
  fingerprint:  ["biometric", "identity", "security", "auth"],

  /* ── Data & Analytics ────────────────────────────────── */
  chart:        ["graph", "analytics", "statistics", "data", "visualization"],
  graph:        ["chart", "analytics", "data", "plot"],
  bar:          ["chart", "graph", "histogram", "statistics"],
  pie:          ["chart", "graph", "donut", "percentage", "statistics"],
  line:         ["chart", "graph", "trend", "analytics"],
  analytics:    ["data", "chart", "insights", "metrics", "statistics"],
  dashboard:    ["overview", "home", "metrics", "summary", "panel"],
  report:       ["document", "analytics", "summary", "statistics"],
  trend:        ["analytics", "growth", "direction", "chart"],

  /* ── Commerce & Finance ──────────────────────────────── */
  cart:         ["shopping", "basket", "buy", "purchase", "ecommerce"],
  shopping:     ["cart", "bag", "buy", "store", "ecommerce"],
  bag:          ["shopping", "tote", "carry", "purchase"],
  basket:       ["cart", "shopping", "container"],
  wallet:       ["money", "payment", "finance", "cash", "purse"],
  credit:       ["card", "payment", "finance", "transaction"],
  money:        ["dollar", "currency", "finance", "cash", "payment"],
  dollar:       ["money", "currency", "finance", "price", "cost"],
  currency:     ["money", "dollar", "euro", "exchange", "finance"],
  receipt:      ["invoice", "bill", "transaction", "payment", "ticket"],
  invoice:      ["receipt", "bill", "document", "payment"],
  price:        ["cost", "money", "tag", "value", "amount"],
  gift:         ["present", "reward", "surprise", "box", "package"],

  /* ── Settings & System ───────────────────────────────── */
  settings:     ["gear", "cog", "config", "preferences", "options", "wrench"],
  gear:         ["settings", "cog", "config", "mechanical", "options"],
  cog:          ["gear", "settings", "config", "mechanical"],
  wrench:       ["tool", "settings", "fix", "repair", "configure", "spanner"],
  tool:         ["wrench", "settings", "utility", "fix"],
  config:       ["settings", "gear", "preferences", "setup"],
  preferences:  ["settings", "options", "customize", "personalize"],
  power:        ["on", "off", "shutdown", "restart", "energy"],
  plug:         ["connect", "power", "electricity", "socket", "charge"],
  battery:      ["power", "energy", "charge", "level"],
  wifi:         ["wireless", "network", "internet", "connection", "signal"],
  bluetooth:    ["wireless", "connect", "pair", "device"],
  signal:       ["network", "wifi", "strength", "reception", "antenna"],
  globe:        ["world", "earth", "web", "internet", "global", "language", "i18n"],
  world:        ["globe", "earth", "global", "international"],
  network:      ["connection", "nodes", "system", "topology"],
  server:       ["database", "hosting", "backend", "machine", "rack"],
  database:     ["storage", "data", "server", "table", "records"],
  cloud:        ["storage", "upload", "online", "saas", "hosting", "sky", "weather"],
  terminal:     ["code", "command", "console", "cli", "shell", "prompt"],
  code:         ["programming", "developer", "brackets", "html", "script", "terminal"],
  bug:          ["error", "debug", "issue", "insect", "defect"],
  cpu:          ["processor", "chip", "hardware", "computing"],
  memory:       ["ram", "storage", "chip"],
  hard_drive:   ["storage", "disk", "hdd", "ssd"],
  monitor:      ["screen", "display", "desktop", "tv"],
  laptop:       ["computer", "device", "portable", "notebook"],
  mobile:       ["phone", "smartphone", "device", "cell"],
  smartphone:   ["phone", "mobile", "device", "cell"],
  tablet:       ["device", "ipad", "screen"],
  watch:        ["wearable", "time", "smartwatch", "clock"],
  desktop:      ["monitor", "computer", "screen", "pc"],
  mouse:        ["cursor", "click", "pointer", "device"],
  keyboard:     ["type", "input", "keys", "device"],
  printer:      ["print", "output", "paper"],

  /* ── Nature & Weather ────────────────────────────────── */
  sun:          ["light", "bright", "day", "weather", "solar", "brightness"],
  moon:         ["night", "dark", "lunar", "sleep", "crescent"],
  star:         ["favorite", "rating", "bookmark", "featured", "important", "award"],
  heart:        ["love", "like", "favorite", "health", "care", "life"],
  fire:         ["flame", "hot", "trending", "popular", "burn"],
  water:        ["drop", "liquid", "rain", "fluid"],
  droplet:      ["water", "rain", "liquid", "tear", "drop"],
  rain:         ["weather", "water", "precipitation", "cloud"],
  snow:         ["weather", "cold", "winter", "flake", "ice"],
  wind:         ["weather", "air", "breeze", "blow"],
  lightning:    ["thunder", "electric", "storm", "flash", "bolt", "energy"],
  bolt:         ["lightning", "thunder", "electric", "flash", "energy"],
  thunder:      ["lightning", "storm", "weather"],
  tree:         ["nature", "plant", "forest", "leaf", "environment"],
  leaf:         ["nature", "plant", "green", "eco", "organic"],
  flower:       ["nature", "bloom", "plant", "garden"],
  mountain:     ["landscape", "nature", "terrain", "peak", "outdoor"],
  sunrise:      ["dawn", "morning", "sun", "horizon"],
  sunset:       ["dusk", "evening", "sun", "horizon"],

  /* ── Geometry / Shape modifiers ──────────────────────── */
  circle:       ["round", "dot", "ring", "oval", "ellipse"],
  square:       ["rectangle", "box", "shape"],
  rectangle:    ["square", "box", "shape"],
  triangle:     ["shape", "play", "delta", "arrow"],
  diamond:      ["rhombus", "shape", "gem"],
  hexagon:      ["shape", "polygon", "six"],
  octagon:      ["shape", "polygon", "stop"],

  /* ── Style modifiers ─────────────────────────────────── */
  fill:         ["solid", "filled"],
  filled:       ["solid", "fill"],
  duotone:      ["two tone", "dual", "layered"],
  solid:        ["fill", "filled"],
  thin:         ["light", "hairline", "fine"],
  bold:         ["thick", "heavy", "strong"],
  light:        ["thin", "fine", "lightweight"],
  regular:      ["normal", "default", "standard"],

  /* ── Time ────────────────────────────────────────────── */
  clock:        ["time", "hour", "schedule", "watch", "timer"],
  time:         ["clock", "schedule", "hour", "duration"],
  timer:        ["stopwatch", "countdown", "clock", "duration"],
  calendar:     ["date", "schedule", "event", "month", "day", "planner"],
  date:         ["calendar", "day", "schedule"],
  schedule:     ["calendar", "plan", "event", "agenda", "time"],
  history:      ["past", "log", "undo", "recent", "timeline"],
  hourglass:    ["time", "wait", "loading", "sand", "timer"],

  /* ── Spatial / Map ───────────────────────────────────── */
  map:          ["location", "geography", "navigate", "directions", "atlas"],
  location:     ["pin", "marker", "map", "place", "position", "gps"],
  marker:       ["pin", "location", "map", "point"],
  compass:      ["navigation", "direction", "north", "bearing"],
  navigation:   ["direction", "compass", "route", "navigate"],
  route:        ["path", "direction", "navigation", "road"],
  flag:         ["mark", "report", "country", "milestone", "banner"],

  /* ── Miscellaneous ───────────────────────────────────── */
  bookmark:     ["save", "favorite", "mark", "flag", "ribbon"],
  thumbs:       ["like", "dislike", "vote", "approve", "rate"],
  like:         ["thumbs up", "approve", "favorite", "love"],
  dislike:      ["thumbs down", "disapprove", "reject"],
  emoji:        ["smiley", "face", "emoticon", "reaction"],
  smile:        ["happy", "face", "emoji", "smiley"],
  frown:        ["sad", "unhappy", "face", "emoji"],
  zap:          ["lightning", "flash", "electric", "bolt", "quick", "fast", "energy"],
  rocket:       ["launch", "fast", "speed", "startup", "boost"],
  target:       ["goal", "aim", "focus", "bullseye", "objective"],
  crosshair:    ["target", "aim", "scope", "precision", "focus"],
  award:        ["trophy", "medal", "prize", "achievement", "certificate"],
  trophy:       ["award", "winner", "prize", "achievement", "cup"],
  medal:        ["award", "achievement", "badge", "ribbon"],
  crown:        ["king", "queen", "royal", "premium", "vip"],
  sparkle:      ["magic", "new", "clean", "ai", "glitter", "shine"],
  magic:        ["wand", "sparkle", "auto", "ai", "transform"],
  wand:         ["magic", "auto", "transform", "sparkle"],
  palette:      ["color", "design", "art", "paint", "theme"],
  paint:        ["color", "brush", "art", "palette", "fill"],
  brush:        ["paint", "draw", "art", "design"],
  ruler:        ["measure", "size", "dimension", "tool"],
  crop:         ["trim", "cut", "resize", "frame"],
  layers:       ["stack", "overlap", "z-index", "depth", "arrange"],
  component:    ["module", "block", "widget", "element", "piece"],
  puzzle:       ["component", "piece", "plugin", "extension"],
  package:      ["box", "deliver", "product", "parcel", "ship"],
  box:          ["package", "container", "crate", "square"],
  truck:        ["delivery", "shipping", "transport", "vehicle"],
  ship:         ["transport", "boat", "vessel", "delivery"],
  airplane:     ["flight", "travel", "trip", "plane", "air"],
  plane:        ["airplane", "flight", "travel", "air"],
  car:          ["vehicle", "auto", "drive", "transport"],
  bicycle:      ["bike", "cycle", "transport", "pedal"],
  building:     ["office", "company", "house", "structure", "architecture"],
  office:       ["building", "work", "company", "business"],
  briefcase:    ["work", "business", "job", "portfolio", "professional"],
  coffee:       ["cup", "drink", "cafe", "break", "beverage", "mug"],
  food:         ["meal", "eat", "restaurant", "utensil"],
  pizza:        ["food", "slice", "meal"],
  utensils:     ["food", "eat", "fork", "knife", "dining", "cutlery"],
  wine:         ["drink", "glass", "alcohol", "beverage"],
  beer:         ["drink", "glass", "alcohol", "beverage"],
  glass:        ["cup", "drink", "beverage"],
  graduation:   ["education", "school", "cap", "degree", "academic"],
  book:         ["read", "education", "library", "manual", "knowledge"],
  education:    ["school", "learn", "study", "academic"],
  lightbulb:    ["idea", "insight", "innovation", "light", "lamp", "inspiration"],
  bulb:         ["idea", "lightbulb", "innovation", "bright"],
  idea:         ["lightbulb", "innovation", "creative", "insight"],
  megaphone:    ["announce", "promotion", "marketing", "loud", "broadcast"],
  speaker2:     ["announce", "broadcast", "public"],
  hand:         ["point", "gesture", "cursor", "touch", "finger", "click"],
  pointer:      ["cursor", "hand", "click", "mouse", "select"],
  cursor:       ["pointer", "mouse", "click", "select", "hand"],
  touch:        ["tap", "finger", "gesture", "press"],
  gesture:      ["swipe", "touch", "interact", "hand"],
  accessibility:["a11y", "inclusive", "disability", "universal"],
  wheelchair:   ["accessibility", "disability", "a11y"],
  translate:    ["language", "i18n", "localize", "globe"],
  language:     ["translate", "i18n", "globe", "localize"],
  type:         ["text", "font", "typography", "character"],
  text:         ["type", "font", "typography", "string"],
  font:         ["text", "type", "typography"],
  bold2:        ["text", "format", "strong", "weight"],
  italic:       ["text", "format", "emphasis", "slant"],
  underline:    ["text", "format", "decoration"],
  strikethrough:["text", "format", "deleted", "removed"],
  align:        ["text", "layout", "justify", "position"],
  indent:       ["text", "paragraph", "margin", "tab"],
  heading:      ["title", "text", "h1", "h2", "header"],
  paragraph:    ["text", "body", "content"],
  quote:        ["blockquote", "citation", "reference"],
  highlight:    ["marker", "emphasis", "selection", "attention"],
  color:        ["palette", "paint", "swatch", "hue"],
  swatch:       ["color", "sample", "palette"],
  contrast:     ["brightness", "dark", "light", "accessibility"],
  brightness:   ["sun", "light", "contrast", "display"],
  dark:         ["night", "moon", "theme", "mode"],
  theme:        ["style", "mode", "skin", "appearance"],
  mode:         ["theme", "switch", "toggle", "state"],
  appearance:   ["theme", "look", "style", "display"],
  qr:           ["code", "scan", "barcode", "square"],
  barcode:      ["scan", "product", "code", "stripe"],
  api:          ["endpoint", "integration", "interface", "connect"],
  webhook:      ["api", "callback", "event", "hook"],
  plugin:       ["extension", "addon", "module", "integrate"],
  extension:    ["plugin", "addon", "module"],
  widget:       ["component", "module", "element", "block"],
  template:     ["layout", "blueprint", "pattern", "preset"],
  duplicate:    ["copy", "clone", "replicate"],
  merge:        ["combine", "join", "unite", "consolidate"],
  split:        ["divide", "separate", "branch", "fork"],
  branch:       ["git", "fork", "split", "version"],
  fork:         ["branch", "split", "copy", "diverge"],
  commit:       ["save", "git", "version", "checkpoint"],
  version:      ["history", "revision", "iteration"],
  iteration:    ["repeat", "version", "cycle", "loop"],
  loop:         ["repeat", "cycle", "iteration", "infinite"],
  infinity:     ["loop", "unlimited", "forever", "eternal"],
  hash:         ["number", "pound", "tag", "octothorpe"],
  at:           ["email", "mention", "address", "symbol"],
  ampersand:    ["and", "symbol"],
  percent:      ["percentage", "ratio", "discount"],
  info2:        ["information", "help", "about", "circle i"],
  i:            ["information", "info", "about", "details"],
  more:         ["dots", "ellipsis", "options", "overflow", "actions", "kebab"],
  dots:         ["more", "ellipsis", "options", "overflow", "menu"],
  ellipsis:     ["more", "dots", "options", "overflow"],
  kebab:        ["more", "dots vertical", "options", "menu"],
  meatball:     ["more", "dots horizontal", "options", "menu"],
  options:      ["settings", "more", "menu", "preferences"],
  overflow:     ["more", "hidden", "scroll", "truncate"],
  maximize:     ["fullscreen", "expand", "enlarge", "resize"],
  minimize:     ["reduce", "shrink", "collapse", "resize"],
  fullscreen:   ["maximize", "expand", "immersive"],
  resize:       ["scale", "size", "adjust", "stretch"],
  crop2:        ["trim", "cut", "frame", "resize"],
  aspect:       ["ratio", "proportion", "size"],
  ratio:        ["proportion", "aspect", "percentage"],
  snap:         ["align", "grid", "guide", "magnetic"],
  guide:        ["help", "tutorial", "line", "rule"],
  ruler2:       ["measure", "size", "dimension", "tool"],
  archive2:     ["store", "save", "compress", "backup"],
  backup:       ["save", "archive", "copy", "restore"],
  restore:      ["undo", "backup", "recover", "revert"],
  log:          ["history", "record", "audit", "journal"],
  activity:     ["log", "history", "recent", "feed", "pulse"],
  feed:         ["activity", "stream", "news", "rss"],
  rss:          ["feed", "subscribe", "news"],
  subscribe:    ["follow", "notification", "rss", "mail"],
  follow:       ["subscribe", "track", "watch"],
  notify:       ["bell", "alert", "notification"],
  announcement: ["megaphone", "news", "broadcast", "notice"],
  news:         ["article", "announcement", "feed", "press"],
  blog:         ["article", "post", "write", "content"],
  article:      ["news", "blog", "post", "content", "story"],
  post:         ["article", "blog", "publish", "content"],
  publish:      ["post", "release", "deploy", "live"],
  draft:        ["unpublished", "work in progress", "pending", "edit"],
  archive3:     ["old", "stored", "past", "backup"],
  visible:      ["show", "eye", "display", "appear"],
  hidden:       ["hide", "invisible", "eye off", "conceal"],
  show:         ["visible", "display", "reveal", "eye"],
  hide:         ["hidden", "invisible", "conceal", "eye off"],
  preview:      ["view", "eye", "look", "inspect"],
  inspect:      ["examine", "debug", "analyze", "view"],
  debug:        ["bug", "inspect", "fix", "troubleshoot"],
  test:         ["check", "verify", "validate", "experiment"],
  experiment:   ["test", "ab", "trial", "lab"],
  lab:          ["experiment", "flask", "test", "science"],
  flask:        ["lab", "experiment", "science", "beaker"],
  beaker:       ["flask", "lab", "science", "chemistry"],
  microscope:   ["science", "zoom", "inspect", "analyze"],
  telescope:    ["view", "distant", "explore", "astronomy"],
  binoculars:   ["view", "search", "explore", "look"],
  focus:        ["target", "center", "attention", "crosshair"],
  center:       ["align", "middle", "focus"],
  align2:       ["position", "arrange", "distribute", "layout"],
  distribute:   ["space", "arrange", "align", "even"],
  space:        ["gap", "padding", "margin", "distribute"],
  gap:          ["space", "padding", "spacing"],
  padding:      ["space", "margin", "inset"],
  margin:       ["space", "padding", "offset"],
  border:       ["outline", "stroke", "edge", "frame"],
  frame:        ["border", "container", "window", "box"],
  window:       ["frame", "panel", "screen", "app"],
  app:          ["application", "mobile", "window", "program"],
  application:  ["app", "software", "program"],
  software:     ["app", "application", "program"],
  hardware:     ["device", "physical", "equipment"],
  device:       ["hardware", "phone", "tablet", "computer"],
  sync:         ["refresh", "update", "synchronize", "arrows"],
  connect:      ["link", "join", "plug", "pair"],
  disconnect:   ["unlink", "separate", "unplug", "break"],
  pair:         ["connect", "bluetooth", "link", "match"],
  match:        ["pair", "equal", "same", "compare"],
  compare:      ["diff", "match", "contrast", "side by side"],
  diff:         ["compare", "change", "delta", "version"],
  change:       ["edit", "modify", "update", "alter"],
  update:       ["refresh", "change", "modify", "new version"],
  new:          ["add", "create", "fresh", "recent", "plus"],
  recent:       ["new", "latest", "history", "time"],
  old:          ["archive", "past", "outdated", "legacy"],
  legacy:       ["old", "deprecated", "outdated"],
  deprecated:   ["old", "removed", "legacy", "obsolete"],
  trending:     ["popular", "fire", "hot", "growth", "analytics"],
  popular:      ["trending", "hot", "featured", "top"],
  featured:     ["star", "highlight", "promoted", "top"],
  verified:     ["check", "badge", "confirmed", "authentic", "approved"],
  certified:    ["verified", "badge", "approved", "official"],
  official:     ["verified", "certified", "authentic"],
  premium:      ["crown", "pro", "vip", "paid", "upgrade"],
  pro:          ["premium", "professional", "advanced"],
  free:         ["no cost", "open", "available"],
  open:         ["unlock", "public", "expand", "accessible"],
  closed:       ["lock", "private", "restricted"],
  public:       ["open", "visible", "shared", "global"],
  private:      ["lock", "hidden", "restricted", "personal"],
  restricted:   ["lock", "limited", "blocked", "forbidden"],
  blocked:      ["restricted", "banned", "forbidden", "stop"],
  ban:          ["block", "prohibit", "forbidden", "no"],
  forbidden:    ["ban", "block", "restricted", "no entry"],
  allowed:      ["permitted", "approved", "authorized"],
  authorized:   ["allowed", "approved", "authenticated"],
  authenticated:["login", "authorized", "verified"],
  login:        ["sign in", "auth", "account", "credential"],
  logout:       ["sign out", "exit", "disconnect"],
  signin:       ["login", "authenticate", "enter"],
  signup:       ["register", "create account", "join"],
  register:     ["signup", "create", "join", "enroll"],
  join:         ["signup", "register", "enter", "connect"],
  leave:        ["exit", "depart", "quit", "logout"],
  enter:        ["join", "login", "input", "submit"],
  submit:       ["send", "confirm", "enter", "done"],
  apply:        ["submit", "use", "implement"],
  reset:        ["clear", "restart", "default", "undo"],
  clear:        ["remove", "empty", "reset", "clean"],
  clean:        ["clear", "tidy", "organize", "sparkle"],
  organize:     ["sort", "arrange", "order", "tidy"],
  arrange:      ["organize", "sort", "order", "layout"],
  order:        ["sort", "arrange", "sequence", "rank"],
  rank:         ["order", "sort", "position", "level"],
  level:        ["rank", "tier", "degree", "stage"],
  stage:        ["step", "phase", "level", "progress"],
  phase:        ["stage", "step", "period", "cycle"],
  workflow:     ["process", "flow", "steps", "automation"],
  process:      ["workflow", "flow", "procedure"],
  automation:   ["auto", "workflow", "bot", "script"],
  bot:          ["robot", "automation", "ai", "assistant"],
  robot:        ["bot", "automation", "ai", "machine"],
  ai:           ["artificial intelligence", "smart", "bot", "ml", "sparkle"],
  smart:        ["ai", "intelligent", "auto"],
  magic2:       ["wand", "sparkle", "auto", "ai"],
  compose:      ["write", "create", "edit", "pen"],
  create:       ["new", "add", "make", "compose"],
  make:         ["create", "build", "produce"],
  build:        ["create", "construct", "develop"],
  develop:      ["build", "code", "create", "program"],
  deploy:       ["publish", "release", "launch", "ship"],
  release:      ["deploy", "publish", "version", "launch"],
  launch:       ["deploy", "release", "start", "rocket"],
  start:        ["begin", "play", "launch", "initiate"],
  begin:        ["start", "initiate", "commence"],
  end:          ["stop", "finish", "complete", "terminate"],
  finish:       ["end", "complete", "done"],
  complete:     ["finish", "done", "check", "success"],
  done:         ["complete", "finish", "check", "success"],
  pending:      ["waiting", "queue", "draft", "clock"],
  waiting:      ["pending", "queue", "hourglass", "loading"],
  queue:        ["waiting", "line", "pending", "list"],
  stack:        ["layers", "pile", "collection", "cards"],
  collection:   ["set", "library", "gallery", "group"],
  library:      ["collection", "book", "catalog", "repository"],
  catalog:      ["library", "collection", "directory", "list"],
  directory:    ["folder", "catalog", "list", "index"],
  index:        ["directory", "list", "catalog", "toc"],
  toc:          ["table of contents", "index", "outline"],
  outline:      ["stroke", "line", "border", "hollow", "toc", "structure", "hierarchy"],
  structure:    ["outline", "hierarchy", "tree", "architecture"],
  hierarchy:    ["tree", "structure", "organization", "levels"],
  sitemap:      ["structure", "map", "hierarchy", "navigation"],
  flowchart:    ["diagram", "process", "workflow", "chart"],
  diagram:      ["flowchart", "chart", "schematic", "visual"],
  mind_map:     ["diagram", "brainstorm", "ideas", "connections"],
  whiteboard:   ["canvas", "draw", "brainstorm", "freeform"],
  canvas:       ["whiteboard", "draw", "area", "surface"],
  board:        ["kanban", "panel", "surface", "clipboard"],
  kanban:       ["board", "task", "workflow", "agile"],
  task:         ["todo", "item", "action", "activity"],
  todo:         ["task", "checklist", "item", "action"],
  checklist:    ["todo", "task", "list", "checkbox"],
  milestone:    ["goal", "flag", "achievement", "checkpoint"],
  goal:         ["target", "objective", "milestone", "aim"],
  objective:    ["goal", "target", "purpose", "aim"],
  strategy:     ["plan", "chess", "approach", "tactic"],
  plan:         ["strategy", "schedule", "roadmap", "blueprint"],
  roadmap:      ["plan", "timeline", "strategy", "milestones"],
  timeline:     ["history", "roadmap", "schedule", "sequence"],
  event:        ["calendar", "happening", "occasion", "activity"],
  meeting:      ["call", "conference", "video", "schedule"],
  conference:   ["meeting", "call", "event", "video"],
  presentation: ["slides", "pitch", "deck", "screen"],
  slides:       ["presentation", "deck", "carousel"],
  screen:       ["monitor", "display", "window", "presentation"],
  display:      ["screen", "monitor", "show", "visible"],
  view:         ["eye", "display", "see", "look", "preview"],
  look:         ["view", "see", "eye", "inspect"],
  see:          ["view", "eye", "look", "visible"],
  watch2:       ["view", "observe", "monitor", "track"],
  observe:      ["watch", "monitor", "view", "track"],
  monitor2:     ["watch", "track", "observe", "screen"],
  track:        ["monitor", "follow", "observe", "log"],
  audit:        ["log", "review", "inspect", "compliance"],
  review:       ["audit", "inspect", "feedback", "evaluate"],
  evaluate:     ["review", "assess", "rate", "judge"],
  rate:         ["star", "review", "evaluate", "score"],
  score:        ["rate", "point", "grade", "number"],
  grade:        ["score", "rate", "level", "rank"],
  badge2:       ["achievement", "verified", "status", "icon"],
  status:       ["state", "badge", "indicator", "condition"],
  state:        ["status", "condition", "mode"],
  condition:    ["state", "status", "rule", "if"],
  rule:         ["condition", "policy", "guideline", "line"],
  policy:       ["rule", "guideline", "compliance"],
  guideline:    ["rule", "policy", "recommendation", "standard"],
  standard:     ["guideline", "default", "normal", "specification"],
  specification:["standard", "requirement", "detail", "doc"],
  requirement:  ["specification", "need", "must", "criteria"],
  criteria:     ["requirement", "condition", "rule", "filter"],

  /* ── Interaction hints ───────────────────────────────── */
  tap:          ["click", "press", "touch", "finger"],
  click:        ["tap", "press", "select", "action"],
  press:        ["click", "tap", "hold", "push"],
  hold:         ["press", "long press", "grip"],
  swipe:        ["gesture", "slide", "drag", "scroll"],
  scroll:       ["swipe", "overflow", "vertical", "horizontal"],
  pinch:        ["zoom", "gesture", "scale"],
  spread:       ["zoom", "gesture", "scale", "expand"],
};

function uniqueTags(tags: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const tag of tags) {
    const normalized = tag.trim().toLowerCase();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    result.push(normalized);
  }

  return result;
}

export function buildIconTagsFromName(name: string): string[] {
  const words = name.toLowerCase().split(/[\s\-_\.]+/).filter(Boolean);
  const tags: string[] = [...words];

  for (const word of words) {
    const mapped = NAME_TAG_MAP[word];
    if (!mapped) continue;

    for (const tag of mapped) {
      if (!words.includes(tag)) {
        tags.push(tag);
      }
    }
  }

  return uniqueTags(tags);
}

export function rebuildIconTags(icon: IconItem): IconItem {
  return { ...icon, tags: buildIconTagsFromName(icon.name) };
}

// ──────────────────────────────────────────────────────────────
// 2.  PUBLIC ENRICHMENT FUNCTION
// ──────────────────────────────────────────────────────────────

/**
 * Rebuild tags for every icon using the current name-only rule set.
 * Returns the rebuilt array, or `null` if nothing changed.
 */
export function enrichAllIconTags(icons: IconItem[]): IconItem[] | null {
  const rebuilt = icons.map(rebuildIconTags);
  const changed = rebuilt.some((icon, index) => {
    const previous = icons[index];
    if (icon.tags.length !== previous.tags.length) return true;
    return icon.tags.some((tag, tagIndex) => tag !== previous.tags[tagIndex]);
  });

  return changed ? rebuilt : null;
}
