/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase public front-end config.
//
// Values resolve from Vite env vars at build time so the deploy target
// (AWS Amplify) can inject per-environment values: set
// VITE_SUPABASE_PROJECT_ID / VITE_SUPABASE_PUBLISHABLE_KEY in Amplify's
// environment-variable settings, or in a local `.env`. Real env vars set by
// the build host take precedence over `.env`, which takes precedence over
// the committed fallback literals below.
//
// NOTE: the build scripts scripts/safe-changelog-sync.mjs and
// scripts/generate-icons-json.mjs parse the fallback string literals below
// via regex (and also read these same VITE_* vars from process.env). Keep
// each fallback as a plain quoted string literal.

export const projectId =
  import.meta.env.VITE_SUPABASE_PROJECT_ID || "qcqtnrrprgqlckzywnkt"

export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcXRucnJwcmdxbGNrenl3bmt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MzA4MTUsImV4cCI6MjA4OTIwNjgxNX0.ar0WljUDjGToELURy8JZkrPSroCuBe7GjLRcLMko1Rk"
