/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase public front-end config.
//
// Values resolve from Vite env vars at build time so the deploy target
// (AWS Amplify) can inject per-environment values: set
// VITE_SUPABASE_PROJECT_ID / VITE_SUPABASE_PUBLISHABLE_KEY in Amplify's
// environment-variable settings, or in a local `.env`. Real env vars set by
// the build host take precedence over `.env`, which takes precedence over
// the committed fallback literals below.
//
// NOTE: the build scripts scripts/safe-changelog-sync.mjs and
// scripts/generate-icons-json.mjs parse the fallback string literals below
// via regex (and also read these same VITE_* vars from process.env). Keep
// each fallback as a plain quoted string literal.

// Fallback literals match the committed `.env` (the dnfzdqyiepjzqrigpvzw
// project + its publishable key). They exist only so a missing `.env` / unset
// env var still points at the right project rather than nowhere — `.env` and
// Amplify remain the real source of truth. Keep them in sync with `.env`.
export const projectId =
  import.meta.env.VITE_SUPABASE_PROJECT_ID || "dnfzdqyiepjzqrigpvzw"

export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_AbBNYAJCE4TWCWux_7WYkA_sSM9CMvY"
